MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  RPN:
    PRE_NMS_TOPK_TEST: 1000
    POST_NMS_TOPK_TEST: 300
  ROI_HEADS:
    NAME: "Res5ROIHeads"
DATASETS:
  TRAIN: ("soda_train",)
  TEST: ("soda_test",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.07
  STEPS: (11610, 17400)
  MAX_ITER: 23220
INPUT:
  MIN_SIZE_TRAIN: (800, 800)
VERSION: 2
